import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "About Page",
  description: "Generated by create next app",
};

export default function AboutPage() {
  return (
    <h3 className="p-10 text-center">
      
    </h3>
  )
}
