import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Blog Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="p-20 max-w-3xl mx-auto flex min-h-screen flex-col justify-between items-center">
          <Header />
          <main className="pt-8 pb-8 w-full flex-1">
            {children}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
